Script started on 2019年03月 4日 上午 11:09:48
]0;~
[32mWrench@DESKTOP-QF3FH8R [33m~[0m
$ whoami;pwd
Wrench
/home/Wrench
]0;~
[32mWrench@DESKTOP-QF3FH8R [33m~[0m
$ git config -l
[?1h=[K[?1l>]0;~
[32mWrench@DESKTOP-QF3FH8R [33m~[0m
$ git colne[1Pne[1Pnelneone[C[C https://github.com/Wrencha/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;~
[32mWrench@DESKTOP-QF3FH8R [33m~[0m
$ exit

Script done on 2019年03月 4日 上午 11:11:27
